// step-3/vue-app/src/App.vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <error-component>Esto en un mensaje</error-component>
    <error-component :kind="warning">Esto en un mensaje</error-component>
    <error-component :kind="error">Esto en un mensaje</error-component>
  </div>
</template>

<script>
import 'simple-error-component';

export default {
  name: 'App',
  data() {
    return {
      warning: 'warning',
      error: 'error'
    }
  }
}
</script>

// step-3/react-app/src/App.js
import React from 'react';
import 'simple-error-component';

function App() {
  return (
    <div className="App">
      <error-component>Esto en un mensaje</error-component>
      <error-component kind="warning">Esto en un mensaje</error-component>
      <error-component kind="error">Esto en un mensaje</error-component>
    </div>
  );
}

export default App;
